-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 20:10:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alcortebarber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alcortebarber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alcortebarber` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `alcortebarber` ;

-- -----------------------------------------------------
-- Table `alcortebarber`.`Sites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Sites` (
  `siteId` INT NOT NULL AUTO_INCREMENT,
  `siteName` VARCHAR(50) NOT NULL,
  `siteDirection` VARCHAR(160) NOT NULL,
  `siteSchedule` VARCHAR(200) NOT NULL,
  `sitePhone` VARCHAR(12) NOT NULL,
  `siteDescription` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`siteId`),
  UNIQUE INDEX `siteName` (`siteName` ASC) VISIBLE,
  UNIQUE INDEX `siteDirection` (`siteDirection` ASC) VISIBLE,
  UNIQUE INDEX `sitePhone` (`sitePhone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`Barbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Barbers` (
  `barberId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `barberName` VARCHAR(30) NOT NULL,
  `barberSurname` VARCHAR(60) NOT NULL,
  `barberPicture` VARCHAR(1024) NOT NULL,
  `barberDescription` VARCHAR(1024) NOT NULL,
  `siteIdRef` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`barberId`),
  INDEX `siteIdRef` (`siteIdRef` ASC) VISIBLE,
  CONSTRAINT `barbers_ibfk_1`
    FOREIGN KEY (`siteIdRef`)
    REFERENCES `alcortebarber`.`Sites` (`siteId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Services` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `serviceType` VARCHAR(60) NOT NULL,
  `servicePrice` DECIMAL(5,2) NOT NULL,
  `serviceDuration` DATETIME NOT NULL,
  `serviceDescription` VARCHAR(255) NOT NULL,
  `popularity` INT default 0, -- AÑADIDO EL 27/12/2024 para el trigger de  update_popularity
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`serviceId`),
  UNIQUE INDEX `serviceType` (`serviceType` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`BarberService`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`BarberService` (
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `barberId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `serviceId` INT NOT NULL,
  PRIMARY KEY (`barberId`, `serviceId`),
  INDEX `serviceId` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `barberservice_ibfk_1`
    FOREIGN KEY (`barberId`)
    REFERENCES `alcortebarber`.`Barbers` (`barberId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `barberservice_ibfk_2`
    FOREIGN KEY (`serviceId`)
    REFERENCES `alcortebarber`.`Services` (`serviceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Users` (
  `userId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `passwordHash` VARCHAR(72) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `surname` VARCHAR(50) NULL DEFAULT NULL,
  `role` ENUM('admin', 'user', 'barber') NOT NULL,
  `missingTrack` INT NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `passwordHash` (`passwordHash` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Bookings` (
  `bookingId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `bookingDate` DATETIME NOT NULL,
  `bookingAnnotations` VARCHAR(255) NULL DEFAULT NULL,
  `bookingTransactionId` VARCHAR(255) NULL DEFAULT NULL,
  `bookingPaymentDate` DATETIME NULL DEFAULT NULL,
  `bookingPrice` DECIMAL(5,2) NULL DEFAULT NULL,
  `bookingUserId` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  `bookingSiteId` INT NULL DEFAULT NULL,
  `bookingServiceId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`bookingId`),
  UNIQUE INDEX `bookingDate` (`bookingDate` ASC) VISIBLE,
  UNIQUE INDEX `bookingTransactionId` (`bookingTransactionId` ASC) VISIBLE,
  INDEX `bookingUserId` (`bookingUserId` ASC) VISIBLE,
  INDEX `bookingSiteId` (`bookingSiteId` ASC) VISIBLE,
  INDEX `bookingServiceId` (`bookingServiceId` ASC) VISIBLE,
  CONSTRAINT `bookings_ibfk_1`
    FOREIGN KEY (`bookingUserId`)
    REFERENCES `alcortebarber`.`Users` (`userId`),
  CONSTRAINT `bookings_ibfk_2`
    FOREIGN KEY (`bookingSiteId`)
    REFERENCES `alcortebarber`.`Sites` (`siteId`),
  CONSTRAINT `bookings_ibfk_3`
    FOREIGN KEY (`bookingServiceId`)
    REFERENCES `alcortebarber`.`Services` (`serviceId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`Dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`Dates` (
  `dateId` INT NOT NULL AUTO_INCREMENT,
  `dateDate` DATETIME NOT NULL,
  `dateAvailability` ENUM('0', '4') NOT NULL,
  `dateSiteIdRef` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`dateId`),
  UNIQUE INDEX `dateDate` (`dateDate` ASC) VISIBLE,
  INDEX `dateSiteIdRef` (`dateSiteIdRef` ASC) VISIBLE,
  CONSTRAINT `dates_ibfk_1`
    FOREIGN KEY (`dateSiteIdRef`)
    REFERENCES `alcortebarber`.`Sites` (`siteId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `alcortebarber`.`ServiceSite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alcortebarber`.`ServiceSite` (
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `serviceId` INT NOT NULL,
  `siteId` INT NOT NULL,
  PRIMARY KEY (`serviceId`, `siteId`),
  INDEX `siteId` (`siteId` ASC) VISIBLE,
  CONSTRAINT `servicesite_ibfk_1`
    FOREIGN KEY (`serviceId`)
    REFERENCES `alcortebarber`.`Services` (`serviceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `servicesite_ibfk_2`
    FOREIGN KEY (`siteId`)
    REFERENCES `alcortebarber`.`Sites` (`siteId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
